"""Deleted url from Product

Revision ID: 90223d1b3294
Revises: d6aa3e828bfb
Create Date: 2022-03-08 11:36:52.327610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90223d1b3294'
down_revision = 'd6aa3e828bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
