"""Added column url in Product

Revision ID: d6aa3e828bfb
Revises: d9cc357c7912
Create Date: 2022-03-08 09:57:46.527139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aa3e828bfb'
down_revision = 'd9cc357c7912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
